name: Build and Deploy to AWS EC2 via S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Frontend: Build React app
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Backend: Build Java app
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Backend
        working-directory: ./backend
        run: ./mvnw clean package

      # Prepare deployment bundle
      - name: Prepare Deployment Artifact
        run: |
          mkdir -p deploy/scripts
          cp backend/target/*.war deploy/app.war
          cp -r frontend/build deploy/frontend_build
          cp appspec.yml deploy/
          cp -r scripts/* deploy/scripts/

      - name: Zip Deployment Artifact
        run: zip -r deploy.zip deploy

      # Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://streamscout-deploy-artifacts/deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name StreamScoutApp \
            --deployment-group-name StreamScoutGroup \
            --s3-location bucket=streamscout-deploy-artifacts,key=deploy.zip,bundleType=zip \
            --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2

