name: Build and Deploy to AWS EC2 via S3

on:
  push:
    branches:
      - main   # Or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # If you have backend and frontend, build both accordingly
      # Example: Build React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Example: Build Java backend
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Backend
        working-directory: ./backend
        run: ./mvnw clean package   # or your build command

      - name: Prepare Deployment Artifact
        run: |
          mkdir deploy
          cp backend/target/*.war deploy/app.war
          cp -r frontend/build deploy/frontend_build
          cp appspec.yml deploy/
          cp -r scripts deploy/scripts

      - name: Zip Deployment Artifact
        run: zip -r deploy.zip deploy

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: streamscout-deploy-artifacts 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: .
          DEST_DIR: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name StreamScoutApp \
            --deployment-group-name StreamScoutGroup \
            --s3-location bucket=streamscout-deploy-artifacts,bundleType=zip,key=deploy.zip \
            --region us-east-2

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
