name: Test SCP to EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  scp-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create test file
      run: echo "Hello EC2" > test.txt

    - name: Validate SSH key
      run: |
        if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
          echo "❌ SSH key is missing."
          exit 1
        fi

    - name: SCP test file to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        source: test.txt
        target: ~/test_scp
